version: '2'
services:
    poc6_como_entity_design-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/POC6_COMO_ENTITY_DESIGN/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=poc6_como_entity_design
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
